### ISSUE TITLE
Non-infinite size when raising StopIteration

### ISSUE THREAD

**Issue by havenwood** [zverok/enumerator_generate#3]
It just occurred to me that there are legitimate reasons to `raise StopIteration` with Enumerator.generate. Here's an example:

```ruby
enum = Enumerator.generate('z') do |s|
  s.ord.pred.chr
rescue RangeError
  raise StopIteration
end

enum.count
#=> 123
```

This makes me think I was wrong to assume it's correct to use infinity as the lazily-calculated size in #1.

**Comment by zverok** [comment]
Hmm... Makes sense. Do you think that "lazy count" should be returned back to `nil`, then? Or what?

**Comment by havenwood** [comment]
Yes, I think it should be reverted to `nil`, since I can't think of any way to properly calculate it taking `StopIteration` into account.
